In [1]:
import pandas as pd

In [17]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA

In [3]:
salary = pd.read_csv('/content/datascience_salaries.csv')

In [4]:
salary.head()

,Unnamed: 0,job_title,job_type,experience_level,location,salary_currency,salary
0,0,Data scientist,Full Time,Senior,New York City,USD,149000
1,2,Data scientist,Full Time,Senior,Boston,USD,120000
2,3,Data scientist,Full Time,Senior,London,USD,68000
3,4,Data scientist,Full Time,Senior,Boston,USD,120000
4,5,Data scientist,Full Time,Senior,New York City,USD,149000

In [5]:
salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1171 entries, 0 to 1170
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1171 non-null   int64
 1   job_title         1171 non-null   object
 2   job_type          1171 non-null   object
 3   experience_level  1171 non-null   object
 4   location          1171 non-null   object
 5   salary_currency   1171 non-null   object
 6   salary            1171 non-null   int64
dtypes: int64(2), object(5)
memory usage: 64.2+ KB

In [7]:
salary.describe()

        Unnamed: 0         salary
count  1171.000000    1171.000000
mean    931.620837   64836.037575
std     647.445266   32551.767046
min       0.000000   30000.000000
25%     364.500000   45000.000000
50%     815.000000   63000.000000
75%    1504.500000   68000.000000
max    2259.000000  228000.000000

In [11]:
salary.duplicated().sum()

np.int64(0)

In [14]:
salary.isna().sum()

Unnamed: 0          0
job_title           0
job_type            0
experience_level    0
location            0
salary_currency     0
salary              0
dtype: int64

In [15]:
salary['experience_level'].unique()

array(['Senior', 'Entry', 'Mid', 'Executive'], dtype=object)

In [18]:
# Normalize salary
scaler = MinMaxScaler()
salary['salary_normalized'] = scaler.fit_transform(salary[['salary']])
print(salary[['salary', 'salary_normalized']].head())

   salary  salary_normalized
0  149000           0.601010
1  120000           0.454545
2   68000           0.191919
3  120000           0.454545
4  149000           0.601010

In [19]:
# Encode categorical variables
salary_encoded = pd.get_dummies(
    salary,
    columns=['job_title','job_type','experience_level','location','salary_currency'],
    drop_first=True
)

In [20]:
# PCA dimensionality reduction
pca = PCA(n_components=2)
pca_features = pca.fit_transform(salary_encoded)

In [21]:
# Salary statistics
salary_stats = salary.groupby('experience_level')['salary'].agg(['mean','median'])

print(salary_stats)

                          mean   median
experience_level
Entry             36111.111111  30000.0
Executive         76076.923077  46000.0
Mid               51786.885246  51000.0
Senior            75088.033012  68000.0