**Exercise 1: Introduction to Data Analysis (Easy)**

What is Data Analysis?

Data analysis is the process of collecting, organizing, cleaning, and examining data to discover meaningful insights and support decision-making. It involves using statistical methods, programming tools, and visualization techniques to transform raw data into useful information. Data analysts work with structured and unstructured datasets to identify patterns, trends, and relationships that help organizations understand performance and predict future outcomes.

Why is Data Analysis Important in Modern Contexts?

In today’s digital world, enormous amounts of data are generated every second through online platforms, financial systems, healthcare devices, and business operations. Data analysis is essential because it enables organizations to make informed decisions instead of relying on intuition alone.

Modern companies use data analysis to improve efficiency, reduce risks, personalize customer experiences, and gain competitive advantages. Governments and researchers also depend on data analysis to solve social, economic, and environmental challenges. With the growth of artificial intelligence and big data technologies, data analysis has become a key skill in nearly every industry.

Areas Where Data Analysis Is Applied Today

1. Business and Finance
Companies analyze sales data, customer behavior, and financial performance to optimize strategies and increase profitability. Financial analysts use data to forecast revenue, manage budgets, detect fraud, and assess investment risks.

2. Healthcare
Healthcare organizations apply data analysis to monitor patient outcomes, improve diagnostics, and support medical research. For example, hospitals analyze patient data to predict disease risks, optimize treatment plans, and improve resource allocation.

3. Marketing and E-Commerce
Marketing teams use data analysis to understand customer preferences, measure campaign performance, and personalize recommendations. Online platforms analyze browsing and purchasing behavior to increase customer engagement and sales conversions.

Conclusion

Data analysis plays a critical role in modern society by turning data into actionable knowledge. As industries continue to digitize and rely on data-driven strategies, the importance of data analysis will continue to grow. Professionals who can analyze and interpret data help organizations innovate, improve decision-making, and create better products and services.

**Exercise 2: Dataset Loading and Initial Analysis**

In [1]:
pip install pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
ERROR: Could not find a version that satisfies the requirement as (from versions: none)
ERROR: No matching distribution found for as

In [2]:
pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2026.2.25)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.4.4)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.5.1)

In [3]:
# Upload kaggle.json file (Run this cell and select your kaggle.json file through the file picker)
from google.colab import files
uploaded = files.upload()

# Make directory named kaggle and copy kaggle.json file there
!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle/

# Change the permissions of the file
!chmod 600 ~/.kaggle/kaggle.json

Saving kaggle.json to kaggle.json

In [4]:
!kaggle datasets download -d arshid/iris-flower-dataset

Dataset URL: https://www.kaggle.com/datasets/arshid/iris-flower-dataset
License(s): CC0-1.0
Downloading iris-flower-dataset.zip to /content
  0% 0.00/0.99k [00:00<?, ?B/s]
100% 0.99k/0.99k [00:00<00:00, 3.05MB/s]

In [5]:
import pandas as pd

In [9]:
mental_health = pd.read_csv("Mental health Depression disorder Data.csv")

/tmp/ipykernel_2655/2644170009.py:1: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  mental_health = pd.read_csv("Mental health Depression disorder Data.csv")

In [10]:
display(mental_health.head())

,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260

In [11]:
display(mental_health.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108553 entries, 0 to 108552
Data columns (total 11 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   index                      108553 non-null  int64
 1   Entity                     108553 non-null  object
 2   Code                       103141 non-null  object
 3   Year                       108553 non-null  object
 4   Schizophrenia (%)          25875 non-null   object
 5   Bipolar disorder (%)       19406 non-null   object
 6   Eating disorders (%)       100236 non-null  object
 7   Anxiety disorders (%)      6468 non-null    float64
 8   Drug use disorders (%)     6468 non-null    float64
 9   Depression (%)             6468 non-null    float64
 10  Alcohol use disorders (%)  6468 non-null    float64
dtypes: float64(4), int64(1), object(6)
memory usage: 9.1+ MB

None

In [12]:
sleep_time = pd.read_csv("Time Americans Spend Sleeping.csv")

In [ ]:
sleep_time.head()

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

In [13]:
sleep_time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 945 entries, 0 to 944
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   index                     945 non-null    int64
 1   Year                      945 non-null    int64
 2   Period                    945 non-null    object
 3   Avg hrs per day sleeping  945 non-null    float64
 4   Standard Error            945 non-null    float64
 5   Type of Days              945 non-null    object
 6   Age Group                 945 non-null    object
 7   Activity                  945 non-null    object
 8   Sex                       945 non-null    object
dtypes: float64(2), int64(2), object(5)
memory usage: 66.6+ KB

In [14]:
credit_card_db = pd.read_csv("clean_dataset.csv")

In [ ]:
credit_card_db.head()

,Gender,Age,Debt,Married,BankCustomer,Industry,Ethnicity,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,1,30.83,0.000,1,1,Industrials,White,1.25,1,1,1,0,ByBirth,202,0,1
1,0,58.67,4.460,1,1,Materials,Black,3.04,1,1,6,0,ByBirth,43,560,1
2,0,24.50,0.500,1,1,Materials,Black,1.50,1,0,0,0,ByBirth,280,824,1
3,1,27.83,1.540,1,1,Industrials,White,3.75,1,1,5,1,ByBirth,100,3,1
4,1,20.17,5.625,1,1,Industrials,White,1.71,1,0,0,0,ByOtherMeans,120,0,1

In [15]:
credit_card_db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          690 non-null    int64
 1   Age             690 non-null    float64
 2   Debt            690 non-null    float64
 3   Married         690 non-null    int64
 4   BankCustomer    690 non-null    int64
 5   Industry        690 non-null    object
 6   Ethnicity       690 non-null    object
 7   YearsEmployed   690 non-null    float64
 8   PriorDefault    690 non-null    int64
 9   Employed        690 non-null    int64
 10  CreditScore     690 non-null    int64
 11  DriversLicense  690 non-null    int64
 12  Citizen         690 non-null    object
 13  ZipCode         690 non-null    int64
 14  Income          690 non-null    int64
 15  Approved        690 non-null    int64
dtypes: float64(3), int64(10), object(3)
memory usage: 86.4+ KB

**Exercise 3: Identifying Data Types**

 For the dataset Mental health Depression the columns with quantitative data / numerical data is: 'Year', 'Schizophrenia', 'Bipolar disorder', 'Eating disorders', 'Anxiety disorders', 'Drug use disorders', 'Depression' and 'Alcohol use disorders', and others like 'Entity' and 'Code' are qualitative / categorical. Despite the fact that some of the quantitative indicators are object type, they are precisely quantitative indicators.


For the dataset Time Americans Spend Sleeping disorder Data the columns with quantitative data / numerical data is: 'Year', 'Avg hrs per day sleeping', and 'Standard Error', while other columns like 'Period', 'Type of Days', 'Age Group', 'Activity', and 'Sex' are qualitative / categorical (object type).


For the Credit Card Approvals datasetbthe columns with quantitative data / numerical data is: 'Age','Debt', 'YearsEmployed', 'CreditScore', 'Income', and others like 'Gender', 'Married', 'ZipCode', 'BankCustomer', 'Industry', 'Ethnicity', 'PriorDefault', 'Employed', 'DriversLicense', 'Citizen', 'Approved'. Some of them are numerical, but represents a binary categorical (e.g., 0 for female, 1 for male or 0 for not married, 1 for married), as zip code although numerical, this is often treated as categorical for analysis purposes.

**Exercise 4: Exploring Data Types**

In [16]:
!unzip iris-flower-dataset.zip

Archive:  iris-flower-dataset.zip
  inflating: IRIS.csv

In [17]:
iris_data = pd.read_csv('IRIS.csv')
iris_data.head(5)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [18]:
iris_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

For the Iris dataset the quantitative columns are 'sepal_length', 'sepal_width', 'petal_length' and 'petal_width', and 'species' column is    qualitative.
For sepal and petal there are length and width which is a number and is a quantitave type of data. But 'species' column is a qualitive as it is a name of iris species.

**Exercise 5: Basic Observation Skills in Data Analysis**

In [19]:
sleep_time.head(15)

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both
5,5,2008,Annual,8.60,0.023,All days,15 years and over,Sleeping,Both
6,6,2009,Annual,8.67,0.023,All days,15 years and over,Sleeping,Both
7,7,2010,Annual,8.67,0.024,All days,15 years and over,Sleeping,Both
8,8,2011,Annual,8.71,0.026,All days,15 years and over,Sleeping,Both
9,9,2012,Annual,8.73,0.026,All days,15 years and over,Sleeping,Both
10,10,2013,Annual,8.74,0.027,All days,15 years and over,Sleeping,Both
11,11,2014,Annual,8.80,0.025,All days,15 years and over,Sleeping,Both
12,12,2015,Annual,8.83,0.027,All days,15 years and over,Sleeping,Both
13,13,2016,Annual,8.79,0.028,All days,15 years and over,Sleeping,Both
14,14,2017,Annual,8.80,0.027,All days,15 years and over,Sleeping,Both

For Time Americans Spend Sleeping dataset we can choose column 'Year' and 'Avg hrs per day sleeping'

For the `sleep_time` dataset, here's an analysis of interesting columns:

### Trend Analysis
*   **`Year` and `Avg hrs per day sleeping`**: These two columns are ideal for **trend analysis**. You can plot `Avg hrs per day sleeping` against `Year` to observe how sleeping patterns among Americans have changed over time. This could reveal if people are sleeping more or less over the years, and if there are any significant shifts in sleep duration.

### Group Comparison
*   **`Age Group` and `Avg hrs per day sleeping`**: These columns are excellent for **group comparison**. You can compare the average hours of sleep across different `Age Group` categories (e.g., '15 to 24 years', '25 to 34 years', etc.). This analysis can highlight how sleep duration varies with age.
*   **`Sex` and `Avg hrs per day sleeping`**: Similarly, comparing `Avg hrs per day sleeping` between different `Sex` categories (e.g., 'Both', 'Men', 'Women') can reveal gender-based differences in sleep patterns.
*   **`Type of Days` and `Avg hrs per day sleeping`**: This pair allows for comparing sleep duration on `All days`, `Weekdays`, and `Weekends`. This is useful for understanding how daily schedules influence sleep habits.

### Other Columns
*   **`Standard Error`**: While not directly for trend or group comparison in terms of average values, this column can be used to understand the **reliability of the `Avg hrs per day sleeping` estimates**. A higher standard error suggests more variability or less precision in the average, which can be important context for any findings.
*   **`Period`**: This column indicates whether the data is 'Annual' or from a specific part of the year. It could be used in conjunction with `Year` and `Avg hrs per day sleeping` to see if annual averages hide seasonal variations.

**Exercise 6: Identifying Data Types**
Below are various data sources. Identify whether each one is an example of structured or unstructured data.

A company's financial reports stored in an Excel file - structured data
Photographs uploaded to a social media platform - unstructured data
A collection of news articles on a website - unstructured data
Inventory data in a relational database - structured data
Recorded interviews from a market research study - unstructured data

**Exercise 7: Transformation Exercise**
For each of the following unstructured data sources, propose a method to convert it into structured data. Explain your reasoning.

1. A series of blog posts about travel experiences. We can use NLP techniques can be applied to extract entities (e.g., destinations, activities, cuisines), sentiments (positive, negative about experiences), keywords, and topics. This information can then be stored in a relational database or a JSON/CSV format.
Audio recordings of customer service calls. Blog posts are rich in textual content. By identifying key pieces of information (like locations, dates, ratings, specific experiences, or mentioned businesses), we can populate structured fields in a database. For example, a table could have columns for 'Blog_ID', 'Destination', 'Travel_Date', 'Main_Activity', 'Sentiment_Score', 'Keywords'.
2. Handwritten notes from a brainstorming session. Here is better to use Optical Character Recognition (OCR) technology can be used to convert handwritten text into digital text. Once digitized, further analysis can involve identifying key themes, ideas, action items, participants, and relationships between ideas. This could be stored in a document database or a spreadsheet. Handwritten notes are highly unstructured. OCR provides the first step to make the content machine-readable. Subsequently, human review or more advanced NLP (if handwriting is clear enough and context is rich) can categorize ideas, link them to participants, assign priorities, or identify follow-up actions, forming structured fields like 'Idea_ID', 'Topic', 'Contributor', 'Priority', 'Action_Item', 'Related_Ideas'.
3. A video tutorial on cooking. For this we can use Speech-to-Text (STT) transcription first converts the audio into text. Then, NLP and Text Mining techniques can be used on the transcripts to extract structured information such as customer intent, product/service mentioned, sentiment of the call, resolution status, call duration, and agent ID. Call metadata (timestamp, caller ID) can also be added. Raw audio is difficult to analyze quantitatively. Converting it to text makes it amenable to text analysis. Identifying specific events, keywords, or emotions within the conversation allows for creation of structured records (e.g., 'Call_ID', 'Customer_Sentiment', 'Issue_Category', 'Resolution_Status', 'Product_Mentioned').

**Exercise 8 : Import a file from Kaggle**

In [21]:
train_data = pd.read_csv("train.csv")
train_data.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

**Exercise 9 : Export a dataframe to excel format and JSON format.**

In [22]:
data = {"name":["Jhon", "Man", "Jordan", "David"],"surname":["Smith", "Lee", "Format", "Morgan"],"age": [15, 20, 25, 35]}

simple_data = pd.DataFrame(data)
print(simple_data)

     name surname  age
0    Jhon   Smith   15
1     Man     Lee   20
2  Jordan  Format   25
3   David  Morgan   35

In [23]:
simple_data.to_excel("people_data.xlsx", index=False)

In [24]:
simple_data.to_json("people_data.json", orient="records", indent=4)

**Exercise 10: Reading JSON Data**

In [26]:
posts_data = pd.read_json("posts.json")
posts_data.head(5)

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...